---
# tasks file for ec2-launch

- name: Create EC2 instance/s
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    id: "{{ ec2_launch_id | default(omit) }}"
    count: "{{ ec2_launch_count | default(omit) }}"
    exact_count: "{{ ec2_launch_exact_count | default(omit) }}"
    count_tag: "{{ ec2_launch_count_tag | default(omit) }}"
    image: "{{ ec2_launch_image }}"
    group: "{{ ec2_launch_groups | default(omit) }}"
    instance_tags:
      Name: "{{ ec2_launch_name_tag | default(omit) }}"
      class: "{{ ec2_launch_class_tag | default(omit) }}"
    instance_type: "{{ ec2_launch_instance_type }}"
    key_name: "{{ ec2_launch_key_name | default(omit) }}"
    wait: True
    region: "{{ ec2_launch_region }}"
    state: "{{ ec2_launch_state | default(omit) }}"
  register: ec2_launch

- name: The following instances have been launched
  debug:
    var: ec2_launch

- name: Wait for instance/s to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    search_regex: "OpenSSH"
    timeout: 90
    delay: 20
  when: item.state == "running"
  with_items: "{{ ec2_launch.instances }}"

- name: Add newly created instances to the hosts for the next play
  add_host:
    name: "{{ item.public_ip }}"
    group: just_created
  when: item.state == "running"
  with_items: "{{ ec2_launch.instances }}"
